apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: deno-fresh-template

build:
  artifacts:
    - image: ghcr.io/wcygan/deno-fresh-template/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    tryImportMissing: true
    useDockerCLI: true

profiles:
  - name: remote-push
    build:
      local:
        push: true

manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: fresh-app
    namespace: app
    port: 80
    localPort: 8080
