apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: deno-fresh-template

manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: fresh-app
    namespace: app
    port: 80
    localPort: 8080

